language: java

jdk:
  - oraclejdk8

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt

addons:
  coverity_scan:
    project:
      name: hvidberrrg/the-soon-to-be-famous-kyubot
      version: 1.0
      description: The soon to be famous KyuBOT (build submitted via Travis CI)
    notification_email: hvidberrrg@users.noreply.github.com
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true verify
    branch_pattern: coverity_scan
  sonarcloud:
      organization: "hvidberrrg-github"
      token: ${SONAR_TOKEN}

script:
  - if [ "${COVERITY_SCAN_BRANCH}" == 1 ]; then
      echo "Skipping module tests on Coverity branch/job";
    else
      echo "Running script stage";
      travis_retry mvn clean verify;
      if [ -z "${SONAR_TOKEN}" ]; then
        echo "Sonar analysis is not run";
      else
        mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=hvidberrrg_the-soon-to-be-famous-kyubot -Dsonar.organization=hvidberrrg-github -Dsonar.login=${SONAR_TOKEN};
      fi;
    fi
