language: java

jdk:
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: Lx8sOuRVIJb5SYrSaclM+zQp8GjFtSgPsO8zQQusVI204zxBqE3llKZyC82Fd02KQgYh+p2AltoaKhT88kxSGFP/RcCqQj1KV8kzK/a8b8s3+MTt6v+WuqKxJWQguNeLOfFWR3RmQVrV6Y7butzNCMU5bYX6JnMkULowXZH01Jzfq5gtrqX1i4qGrzozx52dcTxYzJfN7FaN8NZC07NbUC+13D5Om6V0qpBTg5WCROG72vwcxKeTT3nxqtohuR9WgjWwJ05bXmP3/spLWnZVaHrGRWBeUDfaYkHCVFQPrBJXteuU6vAjcyK1DwbViQ71+bfYOKhvt+xwLZlLAhdBclzUgnUUGkOQSFU63zH78HWy5Cqj5MPJZpwXNBr2aZg3tdbeWCkGPGGx+e76xJ/jbIQ5J7Pc8+etdWg+GoC3u9OJ0SwIwCtuwaTBjGURqOCus5eZety/2r0hipPPiLY5Ej6qV4H1gj6gP6b7UsER21dTx4d2Dh1NzxHx43TD/kcsSG/lrMRDO/M+1dAbck4/Xp8mELic5k0944q/gdZswmMdmxebqfrdNyZmdo0BYoPdOGRVRwz98qBz2ZHzfmgM7EM4TYGGBsVvlv/g6rBHE28ctdXqaC7/c2AKYni/roQRKbivs6itmu6lsm7s3gs3/q0M9s5vj5hFg0ydwvK/Qso=

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt

addons:
  coverity_scan:
    project:
      name: hvidberrrg/the-soon-to-be-famous-kyubot
      version: 1.0
      description: The soon to be famous KyuBOT (build submitted via Travis CI)
    notification_email: hvidberrrg@users.noreply.github.com
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true verify
    branch_pattern: coverity_scan
  sonarcloud:
      organization: "hvidberrrg-github"
      token: ${SONAR_TOKEN}

script:
  - if [ "${COVERITY_SCAN_BRANCH}" == 1 ]; then
      echo "Skipping module tests on Coverity branch/job";
    else
      echo "Running script stage";
      travis_retry mvn clean verify;
      # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
      travis_retry mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar;
    fi
