language: java

jdk:
  - oraclejdk8

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt

addons:
  sonarcloud:
      organization: "hvidberrrg-github"
      token: ${SONAR_TOKEN}

# We do the Coverity Scan by hand rather than use the coverity addon. This way we can
# ensure that COVERITY_SCAN_TOKEN is set. This approach is inspired by:
# https://chromium.googlesource.com/breakpad/breakpad/+/master/scripts/travis-build.sh
# Also there is the issue of matrix explosion: https://github.com/travis-ci/travis-ci/issues/1975
script:
  - if [ "${TRAVIS_BRANCH}" == "coverity_scan" ]; then
      echo "Skipping module tests on Coverity branch/job";
      if [ -z "${COVERITY_SCAN_TOKEN}" ]; then
        export COVERITY_SCAN_PROJECT_NAME="${TRAVIS_REPO_SLUG}";
        export COVERITY_SCAN_NOTIFICATION_EMAIL="hvidberrrg@users.noreply.github.com";
        export COVERITY_SCAN_BUILD_COMMAND="mvn install";
        export COVERITY_SCAN_BUILD_COMMAND_PREPEND="mvn clean";
        export COVERITY_SCAN_BRANCH_PATTERN="master";
        export COVERITY_SCAN_TOKEN;
        curl -s "https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh" | bash || :;
      else
        echo "Coverity scan is not run";
      fi;

    else
      echo "Running script stage";
      travis_retry mvn clean verify;
      if [ -z "${SONAR_TOKEN}" ]; then
        echo "Sonar analysis is not run";
      else
        mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=hvidberrrg_the-soon-to-be-famous-kyubot -Dsonar.organization=hvidberrrg-github -Dsonar.login=${SONAR_TOKEN};
      fi;
    fi
